# Generated by Django 2.0.7 on 2018-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('pretty_picture', models.ImageField(upload_to='')),
                ('activities', models.TextField()),
                ('optimal_visiting_season', models.CharField(max_length=10)),
            ],
        ),
    ]
